services:
  - type: web
    name: ssh-vpn-bot
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: ADMIN_IDS
        value: "123456789"  # Replace with your Telegram ID
    plan: free
    numInstances: 1
